# Generated by Django 4.1.5 on 2023-07-31 14:38

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('eq_length', models.IntegerField(default=5)),
                ('eq_count', models.IntegerField(default=1)),
                ('operators', models.TextField(default='+-')),
                ('equalities', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, null=True, size=None)),
                ('resettable', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=10)),
                ('play_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('games', models.ManyToManyField(blank=True, related_name='tournaments', to='nerdle_api.game')),
                ('players', models.ManyToManyField(blank=True, related_name='players', to='nerdle_api.player')),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equality', models.CharField(blank=True, max_length=20, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('results', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, null=True, size=None)),
                ('eqs_state', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), blank=True, null=True, size=None)),
                ('finished', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nerdle_api.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nerdle_api.player')),
            ],
        ),
        migrations.CreateModel(
            name='GamesSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Game Summary',
                'verbose_name_plural': 'Games Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nerdle_api.game',),
        ),
    ]
