# Generated by Django 4.1.5 on 2023-08-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerdle_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='error_type',
            field=models.CharField(choices=[('L', 'INVALID LENGTH'), ('E', 'NOT EQUAL'), ('M', 'MANY EQUALS'), ('S', 'INVALID SYMBOL'), ('R', 'NO NUMBER ON RIGHT'), ('I', 'INEQUALITY')], default=None, max_length=1, null=True),
        ),
    ]
